#Web服务器：apache | nginx，通过交互式选择获取
prestashop_webs: apache

prestashop_vhost_dir: /etc/httpd/vhost
prestashop_vhost_src: vhost.conf
prestashop_service: httpd
prestashop_owner: apache
prestashop_db_password: "123456"
prestashop_name: prestashop
prestashop_title: PrestaShop
# 此链接需要定期维护
prestashop_download_url: https://download.prestashop.com/download/releases/prestashop_1.7.6.5.zip

